// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace MusicIdentificationSystem.EF.Interfaces
{
    using MusicIdentificationSystem.EF.Entities;

    public partial interface IDb : System.IDisposable
    {
        System.Data.Entity.DbSet<FingerprintEntity> Fingerprints { get; set; } // Fingerprints
        System.Data.Entity.DbSet<StreamStationEntity> StreamStations { get; set; } // StreamStations
        System.Data.Entity.DbSet<SubFingerprintEntity> SubFingerprints { get; set; } // SubFingerprints
        System.Data.Entity.DbSet<TrackEntity> Tracks { get; set; } // Tracks

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get; }
        System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get; }
        System.Data.Entity.Database Database { get; }
        System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
        System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity);
        System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors();
        System.Data.Entity.DbSet Set(System.Type entityType);
        System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();

        // Stored Procedures
        int SpDeleteTrack(int? id);
        // SpDeleteTrackAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        System.Collections.Generic.List<SpInsertFingerprintReturnModel> SpInsertFingerprint(byte[] signature, int? trackId);
        System.Collections.Generic.List<SpInsertFingerprintReturnModel> SpInsertFingerprint(byte[] signature, int? trackId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<SpInsertFingerprintReturnModel>> SpInsertFingerprintAsync(byte[] signature, int? trackId);

        System.Collections.Generic.List<SpInsertSubFingerprintReturnModel> SpInsertSubFingerprint(int? trackId, int? sequenceNumber, double? sequenceAt, long? hashTable0, long? hashTable1, long? hashTable2, long? hashTable3, long? hashTable4, long? hashTable5, long? hashTable6, long? hashTable7, long? hashTable8, long? hashTable9, long? hashTable10, long? hashTable11, long? hashTable12, long? hashTable13, long? hashTable14, long? hashTable15, long? hashTable16, long? hashTable17, long? hashTable18, long? hashTable19, long? hashTable20, long? hashTable21, long? hashTable22, long? hashTable23, long? hashTable24, string clusters);
        System.Collections.Generic.List<SpInsertSubFingerprintReturnModel> SpInsertSubFingerprint(int? trackId, int? sequenceNumber, double? sequenceAt, long? hashTable0, long? hashTable1, long? hashTable2, long? hashTable3, long? hashTable4, long? hashTable5, long? hashTable6, long? hashTable7, long? hashTable8, long? hashTable9, long? hashTable10, long? hashTable11, long? hashTable12, long? hashTable13, long? hashTable14, long? hashTable15, long? hashTable16, long? hashTable17, long? hashTable18, long? hashTable19, long? hashTable20, long? hashTable21, long? hashTable22, long? hashTable23, long? hashTable24, string clusters, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<SpInsertSubFingerprintReturnModel>> SpInsertSubFingerprintAsync(int? trackId, int? sequenceNumber, double? sequenceAt, long? hashTable0, long? hashTable1, long? hashTable2, long? hashTable3, long? hashTable4, long? hashTable5, long? hashTable6, long? hashTable7, long? hashTable8, long? hashTable9, long? hashTable10, long? hashTable11, long? hashTable12, long? hashTable13, long? hashTable14, long? hashTable15, long? hashTable16, long? hashTable17, long? hashTable18, long? hashTable19, long? hashTable20, long? hashTable21, long? hashTable22, long? hashTable23, long? hashTable24, string clusters);

        System.Collections.Generic.List<SpInsertTrackReturnModel> SpInsertTrack(string isrc, string artist, string title, string album, int? releaseYear, double? length);
        System.Collections.Generic.List<SpInsertTrackReturnModel> SpInsertTrack(string isrc, string artist, string title, string album, int? releaseYear, double? length, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<SpInsertTrackReturnModel>> SpInsertTrackAsync(string isrc, string artist, string title, string album, int? releaseYear, double? length);

        System.Collections.Generic.List<SpReadFingerprintByTrackIdReturnModel> SpReadFingerprintByTrackId(int? trackId);
        System.Collections.Generic.List<SpReadFingerprintByTrackIdReturnModel> SpReadFingerprintByTrackId(int? trackId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<SpReadFingerprintByTrackIdReturnModel>> SpReadFingerprintByTrackIdAsync(int? trackId);

        System.Collections.Generic.List<SpReadFingerprintsByHashBinHashTableAndThresholdReturnModel> SpReadFingerprintsByHashBinHashTableAndThreshold(long? hashBin0, long? hashBin1, long? hashBin2, long? hashBin3, long? hashBin4, long? hashBin5, long? hashBin6, long? hashBin7, long? hashBin8, long? hashBin9, long? hashBin10, long? hashBin11, long? hashBin12, long? hashBin13, long? hashBin14, long? hashBin15, long? hashBin16, long? hashBin17, long? hashBin18, long? hashBin19, long? hashBin20, long? hashBin21, long? hashBin22, long? hashBin23, long? hashBin24, int? threshold);
        System.Collections.Generic.List<SpReadFingerprintsByHashBinHashTableAndThresholdReturnModel> SpReadFingerprintsByHashBinHashTableAndThreshold(long? hashBin0, long? hashBin1, long? hashBin2, long? hashBin3, long? hashBin4, long? hashBin5, long? hashBin6, long? hashBin7, long? hashBin8, long? hashBin9, long? hashBin10, long? hashBin11, long? hashBin12, long? hashBin13, long? hashBin14, long? hashBin15, long? hashBin16, long? hashBin17, long? hashBin18, long? hashBin19, long? hashBin20, long? hashBin21, long? hashBin22, long? hashBin23, long? hashBin24, int? threshold, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<SpReadFingerprintsByHashBinHashTableAndThresholdReturnModel>> SpReadFingerprintsByHashBinHashTableAndThresholdAsync(long? hashBin0, long? hashBin1, long? hashBin2, long? hashBin3, long? hashBin4, long? hashBin5, long? hashBin6, long? hashBin7, long? hashBin8, long? hashBin9, long? hashBin10, long? hashBin11, long? hashBin12, long? hashBin13, long? hashBin14, long? hashBin15, long? hashBin16, long? hashBin17, long? hashBin18, long? hashBin19, long? hashBin20, long? hashBin21, long? hashBin22, long? hashBin23, long? hashBin24, int? threshold);

        System.Collections.Generic.List<SpReadSubFingerprintsByHashBinHashTableAndThresholdWithClustersReturnModel> SpReadSubFingerprintsByHashBinHashTableAndThresholdWithClusters(long? hashBin0, long? hashBin1, long? hashBin2, long? hashBin3, long? hashBin4, long? hashBin5, long? hashBin6, long? hashBin7, long? hashBin8, long? hashBin9, long? hashBin10, long? hashBin11, long? hashBin12, long? hashBin13, long? hashBin14, long? hashBin15, long? hashBin16, long? hashBin17, long? hashBin18, long? hashBin19, long? hashBin20, long? hashBin21, long? hashBin22, long? hashBin23, long? hashBin24, int? threshold, string clusters);
        System.Collections.Generic.List<SpReadSubFingerprintsByHashBinHashTableAndThresholdWithClustersReturnModel> SpReadSubFingerprintsByHashBinHashTableAndThresholdWithClusters(long? hashBin0, long? hashBin1, long? hashBin2, long? hashBin3, long? hashBin4, long? hashBin5, long? hashBin6, long? hashBin7, long? hashBin8, long? hashBin9, long? hashBin10, long? hashBin11, long? hashBin12, long? hashBin13, long? hashBin14, long? hashBin15, long? hashBin16, long? hashBin17, long? hashBin18, long? hashBin19, long? hashBin20, long? hashBin21, long? hashBin22, long? hashBin23, long? hashBin24, int? threshold, string clusters, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<SpReadSubFingerprintsByHashBinHashTableAndThresholdWithClustersReturnModel>> SpReadSubFingerprintsByHashBinHashTableAndThresholdWithClustersAsync(long? hashBin0, long? hashBin1, long? hashBin2, long? hashBin3, long? hashBin4, long? hashBin5, long? hashBin6, long? hashBin7, long? hashBin8, long? hashBin9, long? hashBin10, long? hashBin11, long? hashBin12, long? hashBin13, long? hashBin14, long? hashBin15, long? hashBin16, long? hashBin17, long? hashBin18, long? hashBin19, long? hashBin20, long? hashBin21, long? hashBin22, long? hashBin23, long? hashBin24, int? threshold, string clusters);

        System.Collections.Generic.List<SpReadSubFingerprintsByTrackIdReturnModel> SpReadSubFingerprintsByTrackId(int? trackId);
        System.Collections.Generic.List<SpReadSubFingerprintsByTrackIdReturnModel> SpReadSubFingerprintsByTrackId(int? trackId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<SpReadSubFingerprintsByTrackIdReturnModel>> SpReadSubFingerprintsByTrackIdAsync(int? trackId);

        System.Collections.Generic.List<SpReadTrackByArtistAndSongNameReturnModel> SpReadTrackByArtistAndSongName(string artist, string title);
        System.Collections.Generic.List<SpReadTrackByArtistAndSongNameReturnModel> SpReadTrackByArtistAndSongName(string artist, string title, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<SpReadTrackByArtistAndSongNameReturnModel>> SpReadTrackByArtistAndSongNameAsync(string artist, string title);

        System.Collections.Generic.List<SpReadTrackByIdReturnModel> SpReadTrackById(int? id);
        System.Collections.Generic.List<SpReadTrackByIdReturnModel> SpReadTrackById(int? id, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<SpReadTrackByIdReturnModel>> SpReadTrackByIdAsync(int? id);

        System.Collections.Generic.List<SpReadTrackIsrcReturnModel> SpReadTrackIsrc(string isrc);
        System.Collections.Generic.List<SpReadTrackIsrcReturnModel> SpReadTrackIsrc(string isrc, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<SpReadTrackIsrcReturnModel>> SpReadTrackIsrcAsync(string isrc);

        System.Collections.Generic.List<SpReadTracksReturnModel> SpReadTracks();
        System.Collections.Generic.List<SpReadTracksReturnModel> SpReadTracks(out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<SpReadTracksReturnModel>> SpReadTracksAsync();

    }

}
// </auto-generated>
