// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace MusicIdentificationSystem.EF.Entities
{

    // Fingerprints
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class FingerprintEntity
    {
        public int Id { get; set; } // Id (Primary key)
        public byte[] Signature { get; set; } // Signature (length: 4096)
        public int TrackId { get; set; } // TrackId

        // Foreign keys

        /// <summary>
        /// Parent Track pointed by [Fingerprints].([TrackId]) (FK_Fingerprints_Tracks)
        /// </summary>
        public virtual TrackEntity Track { get; set; } // FK_Fingerprints_Tracks

        public FingerprintEntity()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
