// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace MusicIdentificationSystem.EF.Entities
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class SpReadFingerprintsByHashBinHashTableAndThresholdReturnModel
    {
        public System.Int64 Id { get; set; }
        public System.Int32 TrackId { get; set; }
        public System.Int32 SequenceNumber { get; set; }
        public System.Double SequenceAt { get; set; }
        public System.Int64 HashTable_0 { get; set; }
        public System.Int64 HashTable_1 { get; set; }
        public System.Int64 HashTable_2 { get; set; }
        public System.Int64 HashTable_3 { get; set; }
        public System.Int64 HashTable_4 { get; set; }
        public System.Int64 HashTable_5 { get; set; }
        public System.Int64 HashTable_6 { get; set; }
        public System.Int64 HashTable_7 { get; set; }
        public System.Int64 HashTable_8 { get; set; }
        public System.Int64 HashTable_9 { get; set; }
        public System.Int64 HashTable_10 { get; set; }
        public System.Int64 HashTable_11 { get; set; }
        public System.Int64 HashTable_12 { get; set; }
        public System.Int64 HashTable_13 { get; set; }
        public System.Int64 HashTable_14 { get; set; }
        public System.Int64 HashTable_15 { get; set; }
        public System.Int64 HashTable_16 { get; set; }
        public System.Int64 HashTable_17 { get; set; }
        public System.Int64 HashTable_18 { get; set; }
        public System.Int64 HashTable_19 { get; set; }
        public System.Int64 HashTable_20 { get; set; }
        public System.Int64 HashTable_21 { get; set; }
        public System.Int64 HashTable_22 { get; set; }
        public System.Int64 HashTable_23 { get; set; }
        public System.Int64 HashTable_24 { get; set; }
        public System.String Clusters { get; set; }
        public System.Int64? Id1 { get; set; }
    }

}
// </auto-generated>
