// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace MusicIdentificationSystem.EF.Entities
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class SpReadTracksReturnModel
    {
        public System.Int32 Id { get; set; }
        public System.String ISRC { get; set; }
        public System.String Artist { get; set; }
        public System.String Title { get; set; }
        public System.String Album { get; set; }
        public System.Int32? ReleaseYear { get; set; }
        public System.Double? Length { get; set; }
    }

}
// </auto-generated>
