// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace MusicIdentificationSystem.EF.Mappings
{
    using MusicIdentificationSystem.EF.Context;
    using MusicIdentificationSystem.EF.Entities;

    // Fingerprints
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class FingerprintEntityMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<FingerprintEntity>
    {
        public FingerprintEntityMapping()
            : this("dbo")
        {
        }

        public FingerprintEntityMapping(string schema)
        {
            ToTable("Fingerprints", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Signature).HasColumnName(@"Signature").HasColumnType("varbinary").IsRequired().HasMaxLength(4096);
            Property(x => x.TrackId).HasColumnName(@"TrackId").HasColumnType("int").IsRequired();

            // Foreign keys
            HasRequired(a => a.Track).WithMany(b => b.Fingerprints).HasForeignKey(c => c.TrackId).WillCascadeOnDelete(false); // FK_Fingerprints_Tracks
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
