// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace MusicIdentificationSystem.EF.Mappings
{
    using MusicIdentificationSystem.EF.Context;
    using MusicIdentificationSystem.EF.Entities;

    // StreamStations
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class StreamStationEntityMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<StreamStationEntity>
    {
        public StreamStationEntityMapping()
            : this("dbo")
        {
        }

        public StreamStationEntityMapping(string schema)
        {
            ToTable("StreamStations", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.StationName).HasColumnName(@"StationName").HasColumnType("nvarchar").IsOptional().HasMaxLength(250);
            Property(x => x.Url).HasColumnName(@"URL").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.LocalPath).HasColumnName(@"LocalPath").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsOptional();
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar").IsOptional().HasMaxLength(250);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
